### ISSUE TITLE
Documentation (README.md) error

### ISSUE THREAD

**Issue by litesoft** [amitsingh-007/next-release-tag#1]
The README.md file contains two references to "next_release_version" as the ENV variable name.  That did not work!  However in the code I found "release_tag" which does!

P.S. Thanks for this "action" it is just what I needed!

**Comment by amitsingh-007** [comment]
Oh, thanks for pointing this out. Since this was for my side project, I didnt update the Readme after some releases. Will fix the documentation, thanks.
